- .circleci/config.yml
> patch CircleCI config after migrating repo

- CHANGELOG.md
- cmd/generate/flag.go
- cmd/generate/runner.go
- cmd/lint/flag.go
- cmd/lint/runner.go
- internal/generator/service.go
- pkg/filesystem/error.go
- pkg/filesystem/filesystem.go
Fixes https://github.com/giantswarm/giantswarm/issues/16945. 
:construction_worker: To be merged to `master` branch after #2.
> Use local filesystem instead of github

- CHANGELOG.md
- cmd/generate/flag.go
- cmd/generate/runner.go
- go.mod
- go.sum
- pkg/filesystem/filesystem.go
Fixes https://github.com/giantswarm/giantswarm/issues/16946
> Create App CR when generating config

- CHANGELOG.md
- cmd/generate/runner.go
> Add suffix to generated resources' names

- CHANGELOG.md
- pkg/project/project.go
Towards https://github.com/giantswarm/giantswarm/issues/16947
> Release v0.1.0

- README.md
naming police here 😉
readme change only
> rename CP to MC

- CHANGELOG.md
- main.go
> Add `version` command

- CHANGELOG.md
- cmd/generate/flag.go
- cmd/generate/runner.go
Towards https://github.com/giantswarm/giantswarm/issues/17338
> Fix generated apps namespace

- CHANGELOG.md
- pkg/lint/discovery.go
Towards https://github.com/giantswarm/giantswarm/issues/17276
> Fix unused secret path discovery when secret patch does not exist

- CHANGELOG.md
- cmd/generate/runner.go
Towards https://github.com/giantswarm/giantswarm/issues/17392
> Do not format generated data

- CHANGELOG.md
- pkg/generator/generator.go
> Remove debug line

- CHANGELOG.md
- pkg/lint/discovery.go
Towards https://github.com/giantswarm/giantswarm/issues/17681
> Mark all config fields used in secrets as used

- .nancy-ignore
- CHANGELOG.md
- pkg/lint/fileparser.go
Towards https://github.com/giantswarm/giantswarm/issues/18437
> Improve templatePathPattern regexp

- CHANGELOG.md
- go.mod
- go.sum
> Replace github.com/dgrijalva/jwt-go

- CHANGELOG.md
- go.mod
- go.sum
> Update valuemodifier to v0.4.0

- CHANGELOG.md
- cmd/generate/runner.go
- internal/generator/service.go
- pkg/generator/key/key.go
Towards https://github.com/giantswarm/giantswarm/issues/18191
> Add argo finalizer to enable cascading deletion

- CHANGELOG.md
- pkg/lint/fileparser.go
Closes https://github.com/giantswarm/giantswarm/issues/18933
> Improve include file discovery in linter

- CHANGELOG.md
- cmd/kustomizepatch/runner.go
- go.mod
Logging breaks kustomize output.
> Remove logging

- CHANGELOG.md
- cmd/kustomizepatch/runner.go
> Fix InCluster app config

- CHANGELOG.md
- cmd/generate/runner.go
Fix was made in `kustomizepatch` but we also need it in generate.
> Fix InCluster flag in generate command

- cmd/kustomizepatch/runner.go
- include app config in error output
- add error wrapper
> Make it obvious which app is making konfigure fail

- CHANGELOG.md
- pkg/generator/generator.go
- make errors more descriptive
- update CHANGELOG
> Make giantswarm/config errors more descriptive

- CHANGELOG.md
- pkg/lint/fileparser.go
> Respect template escape markers

- CHANGELOG.md
- pkg/lint/lint.go
Towards: https://github.com/giantswarm/giantswarm/issues/23782
> Update linter to handle sops encrypted files

- .nancy-ignore
- CHANGELOG.md
- internal/sopsenv/sopsenv.go
- internal/sopsenv/sopsenv_test.go
Towards: https://github.com/giantswarm/giantswarm/issues/23966
> Check multi ns

- CHANGELOG.md
- README.md
- cmd/generate/flag.go
- cmd/generate/runner.go
- go.mod
Towards https://github.com/giantswarm/giantswarm/issues/24353
> Support generate working locally with sops and --raw flag

- CHANGELOG.md
- pkg/filesystem/filesystem.go
Towards https://github.com/giantswarm/giantswarm/issues/24353
> Make generate work on shallow copies without tags

- CHANGELOG.md
- go.mod
- go.sum
> Bump valuemodifier to v0.5.2

- CHANGELOG.md
- pkg/filesystem/filesystem.go
> Fix directory where git is run

- .nancy-ignore
> Fix pre-commit checks reported issues

- .github/workflows/zz_generated.create_release.yaml
- .nancy-ignore
> Testing workflow

- CHANGELOG.md
- pkg/generator/generator.go
> Fixing empty secret scenario

- go.mod
- go.sum
> Bump github.com/golang-jwt/jwt/v5

- .nancy-ignore
- cmd/fetchkeys/runner.go
- cmd/generate/runner.go
- cmd/kustomizepatch/runner.go
- cmd/kustomizepatch/runner_test.go
- internal/sopsenv/sopsenv.go
- internal/sopsenv/sopsenv_test.go
- internal/testutils/testutils.go
- pkg/decrypt/yaml_traverser_test.go
- pkg/filesystem/filesystem.go
- pkg/generator/generator_test.go
- pkg/lint/lint.go
- pkg/lint/output.go
Closes https://github.com/giantswarm/giantswarm/issues/32964
> Adapt for golangci-lint v2

- CHANGELOG.md
- pkg/fluxupdater/fluxupdater.go
> Return `Ready` condition message when artifact URL is not found and condition is false

- CHANGELOG.md
- cmd/kustomizepatch/runner.go
- pkg/fluxupdater/fluxupdater.go
- pkg/fluxupdater/fluxupdater_test.go
Towards: https://github.com/giantswarm/giantswarm/issues/33879
> Do not require source-controller service URL anymore
